quarkusio/quarkus-http

core/pom.xml, pom.xml
Relates to: https://github.com/quarkusio/quarkus/issues/3563
=> Use more fine-grained netty dependency in the core module

vertx/src/main/java/io/undertow/vertx/VertxHttpExchange.java
Fixes https://github.com/quarkusio/quarkus/issues/3558
/cc @gsmet 
/cc @stuartwdouglas
=>  async write response in VertxHttpExchange only if callback is not null

vertx/src/main/java/io/undertow/vertx/VertxHttpExchange.java
Fixes https://github.com/quarkusio/quarkus/issues/3372
This is required for https://github.com/quarkusio/quarkus/pull/3404 to land.
I could not find a way to properly add tests for this change on this repo, so I based myself on the tests introduced on the cited PR above. Any pointers are appreciated. 
/cc @stuartwdouglas @gsmet
=> add max entity size in VertxHttpExchange

vertx/src/main/java/io/undertow/vertx/VertxHttpExchange.java
Fixes https://github.com/quarkusio/quarkus/issues/3743
@stuartwdouglas
=>  NPE when QueueListener callback is not defined

pom.xml
Required for https://github.com/quarkusio/quarkus/pull/3746.
=> Update Vert.x version to 3.8.1

core/src/main/java/io/undertow/server/handlers/accesslog/AccessLogHandler.java
Related to [4059](https://github.com/quarkusio/quarkus/issues/4059)
added category to the parameters of access-log
=> access-log - custom category

websockets-jsr/src/main/java/io/undertow/websockets/jsr/WebsocketConnectionBuilder.java
=> Don't use -1 as port

pom.xml
Vert.x updated to 3.9.1
Netty updated to 4.1.49.Final
=> Update Vert.x and Netty versions

websockets-jsr/src/main/java/io/undertow/websockets/jsr/FrameHandler.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedClientEndpoint.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedEndpointTest.java
=> Make sure to send a pong response

vertx/src/main/java/io/undertow/vertx/VertxHttpExchange.java
Porting here the same fix as per merge https://github.com/quarkusio/quarkus/pull/7445/
It resolves the https://github.com/quarkusio/quarkus/issues/7444
=> Fix Monitor bug Quarkus #7444

servlet/src/main/java/io/undertow/servlet/core/ApplicationListeners.java
Supersedes #46. 
- Fix thread-local leak
- Switch to AdoptOpenJDK/install-jdk to install the JVM
=> Fix thread local leak 

servlet/src/test/java/io/undertow/servlet/test/util/TestResourceLoader.java, servlet/src/test/resources/logging.properties
It causesd intermittent failured when testing if-modified-since
=> UNDERTOW-1767 Remove hack from TestResourceLoader

pom.xml, vertx/src/main/java/io/undertow/vertx/PushedHttpServerRequest.java
- integration Vert.x 4.0.3
- update netty to 4.1.60
- Implement HttpServerRequestInternal
=> Update to vertx 4.0.3

core/pom.xml, coverage-report/pom.xml, http-core/pom.xml, pom.xml, servlet/pom.xml, servlet/src/test/java/io/undertow/servlet/test/push/Http2ServerPushTestCase.java, servlet/src/test/java/io/undertow/servlet/test/streams/Http2InputStreamTestCase.java, vertx/pom.xml, vertx/src/main/java/io/undertow/vertx/PushedHttpServerRequest.java, vertx/src/main/java/io/undertow/vertx/VertxHttpExchange.java, vertx/src/main/java/io/undertow/vertx/VertxUndertowEngine.java, websocket/core/pom.xml, websocket/pom.xml, websocket/servlet/pom.xml, websocket/vertx/pom.xml, websocket/vertx/src/main/java/io/undertow/websockets/vertx/VertxWebSocketHttpExchange.java
This PR brings the 4.x branch onto _main_. 
I've created a pushed a 3.x branch already (in case of something that needs to be fixed). 
Once this is merged, we should but a 4.0.0-Final version and update Quarkus.
=> Merge 4.x in main

websocket/vertx/src/main/java/io/undertow/websockets/vertx/VertxWebSocketHttpExchange.java
This is a temp fix, proper support for
extensions will be coming soon.
=> Fix extension issue

.github/workflows/build.yml
Just like https://github.com/quarkusio/quarkus/pull/19414
=> Switch to Eclipse Temurin JDK 8 & 11

core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java, core/src/main/java/io/undertow/server/handlers/AllowedMethodsHandler.java, core/src/main/java/io/undertow/server/handlers/DisallowedMethodsHandler.java
These are the only occurrences of problematic language in this repo.
Not knowing the code, it was hard for me to know if I used the best alternative.
=> Replaced usage of the terms 'blacklist' and 'whitelist'

pom.xml, vertx/src/main/java/io/undertow/vertx/PushedHttpServerRequest.java, websocket/vertx/src/main/java/io/undertow/websockets/vertx/VertxWebSocketHandler.java
- Vert.x 4.2.0 - API changes
- Update to Vert.x 4.2.1 and Netty 4.1.70.Final
=> Vert.x 4.2.1 integration

servlet/src/main/java/io/undertow/servlet/core/ManagedServlet.java, servlet/src/test/java/io/undertow/servlet/test/lifecycle/ThirdServlet.java
Reverts quarkusio/quarkus-http#104
I'm reverting this as it will be applied as part of a bunch of backports from Undertow.
=> Revert "Get rid of SingleThreadModel usage"

websocket/vertx/src/main/java/io/undertow/websockets/vertx/VertxWebSocketHttpExchange.java
Reverts quarkusio/quarkus-http#139 in order to fix https://github.com/quarkusio/quarkus/issues/39082.
=> Revert "Prevent websocket upgrade from replying with `content-length: 0`"

servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriterDelegate.java, servlet/src/test/java/io/undertow/servlet/test/response/writer/ExceptionWriterServlet.java, servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterTestCase.java
- See https://github.com/undertow-io/undertow/pull/1335
=> QUARKUS-4216: ServletPrintWriterDelegate throws exception using OpenJDK 19+
